import type { Metadata } from "next";
import "./globals.css";
import { AsideBar } from "./_section/aside";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";
import NavSection from "./_section/nav";

export const metadata: Metadata = {
    title: "Pawnter",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const defaultOpen = cookieStore.get("sidebar:state")?.value === "true";

    return (
        <html lang="en">
            <body className={`flex items-center justify-center`}>
                <SidebarProvider
                    defaultOpen={defaultOpen}
                    className="container w-auto flex justify-center py-4"
                >
                    <AsideBar />

                    <main
                        className={`relative flex flex-col gap-8 ${
                            defaultOpen ? "w-[calc(100%-10px)]" : "w-full"
                        }`}
                    >
                        <NavSection />

                        {children}
                    </main>
                </SidebarProvider>
            </body>
        </html>
    );
}
