export const MATCH_DATA = {
    event: [
        {
            idEvent: "2101181",
            idAPIfootball: "1231865",
            strEvent: "FC Porto vs Boavista",
            strEventAlternate: "Boavista @ FC Porto",
            strFilename:
                "Portuguese Primeira Liga 2024-12-28 FC Porto vs Boavista",
            strSport: "Soccer",
            idLeague: "4344",
            strLeague: "Portuguese Primeira Liga",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/18vypq1732294716.png",
            strSeason: "2024-2025",
            strDescriptionEN: "",
            strHomeTeam: "FC Porto",
            strAwayTeam: "Boavista",
            intHomeScore: "4",
            intRound: "16",
            intAwayScore: "0",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2024-12-28T20:30:00",
            dateEvent: "2024-12-28",
            dateEventLocal: "2024-12-28",
            strTime: "20:30:00",
            strTimeLocal: "20:30:00",
            strGroup: "",
            idHomeTeam: "134114",
            strHomeTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/xu47rb1628855600.png",
            idAwayTeam: "134588",
            strAwayTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/usi98v1628853974.png",
            intScore: null,
            intScoreVotes: null,
            strResult: "",
            idVenue: "16021",
            strVenue: "Estádio do Dragão",
            strCountry: "Portugal",
            strCity: "",
            strPoster: "",
            strSquare: "",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/5phgee1720533616.jpg",
            strBanner: "",
            strMap: null,
            strTweet1: "",
            strTweet2: "",
            strTweet3: "",
            strVideo: "",
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
        {
            idEvent: "1851172",
            idAPIfootball: "1063772",
            strEvent: "FC Porto vs Boavista",
            strEventAlternate: "Boavista @ FC Porto",
            strFilename:
                "Portuguese Primeira Liga 2024-05-12 FC Porto vs Boavista",
            strSport: "Soccer",
            idLeague: "4344",
            strLeague: "Portuguese Primeira Liga",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/rp1i7e1689641585.png",
            strSeason: "2023-2024",
            strDescriptionEN: "",
            strHomeTeam: "FC Porto",
            strAwayTeam: "Boavista",
            intHomeScore: "2",
            intRound: "33",
            intAwayScore: "1",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2024-05-12T19:30:00",
            dateEvent: "2024-05-12",
            dateEventLocal: "2024-05-12",
            strTime: "19:30:00",
            strTimeLocal: "20:30:00",
            strGroup: null,
            idHomeTeam: "134114",
            strHomeTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/xu47rb1628855600.png",
            idAwayTeam: "134588",
            strAwayTeamBadge:
                "https://www.thesportsdb.com/images/media/team/badge/usi98v1628853974.png",
            intScore: null,
            intScoreVotes: null,
            strResult: "",
            idVenue: "16021",
            strVenue: "Estádio Do Dragão",
            strCountry: "Portugal",
            strCity: "",
            strPoster: "",
            strSquare: "",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/do9uel1691534281.jpg",
            strBanner: "",
            strMap: null,
            strTweet1: "",
            strTweet2: "",
            strTweet3: "",
            strVideo: "https://www.youtube.com/watch?v=j6waNQsxeII",
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
        {
            idEvent: "1593424",
            idAPIfootball: "898871",
            strEvent: "FC Porto vs Boavista",
            strEventAlternate: "Boavista @ FC Porto",
            strFilename:
                "Portuguese Primeira Liga 2023-04-30 FC Porto vs Boavista",
            strSport: "Soccer",
            idLeague: "4344",
            strLeague: "Portuguese Primeira Liga",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/rp1i7e1689641585.png",
            strSeason: "2022-2023",
            strDescriptionEN: "",
            strHomeTeam: "FC Porto",
            strAwayTeam: "Boavista",
            intHomeScore: "1",
            intRound: "30",
            intAwayScore: "0",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2023-04-30T17:00:00+00:00",
            dateEvent: "2023-04-30",
            dateEventLocal: "2023-04-30",
            strTime: "17:00:00",
            strTimeLocal: "18:00:00",
            strGroup: null,
            idHomeTeam: "134114",
            strHomeTeamBadge: null,
            idAwayTeam: "134588",
            strAwayTeamBadge: null,
            intScore: null,
            intScoreVotes: null,
            strResult: "",
            idVenue: "16021",
            strVenue: "Estádio Do Dragão",
            strCountry: "Portugal",
            strCity: "",
            strPoster: "",
            strSquare: "",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/jurdg41659694750.jpg",
            strBanner: "",
            strMap: null,
            strTweet1: "",
            strTweet2: "",
            strTweet3: "",
            strVideo: "https://www.youtube.com/watch?v=xvzY0LSMwuo",
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
        {
            idEvent: "1317468",
            idAPIfootball: "731360",
            strEvent: "FC Porto vs Boavista",
            strEventAlternate: "Boavista @ FC Porto",
            strFilename:
                "Portuguese Primeira Liga 2021-10-30 FC Porto vs Boavista",
            strSport: "Soccer",
            idLeague: "4344",
            strLeague: "Portuguese Primeira Liga",
            strLeagueBadge:
                "https://www.thesportsdb.com/images/media/league/badge/rp1i7e1689641585.png",
            strSeason: "2021-2022",
            strDescriptionEN: null,
            strHomeTeam: "FC Porto",
            strAwayTeam: "Boavista",
            intHomeScore: "4",
            intRound: "10",
            intAwayScore: "1",
            intSpectators: null,
            strOfficial: "",
            strTimestamp: "2021-10-30T16:00:00+00:00",
            dateEvent: "2021-10-30",
            dateEventLocal: null,
            strTime: "16:00:00",
            strTimeLocal: null,
            strGroup: null,
            idHomeTeam: "134114",
            strHomeTeamBadge: null,
            idAwayTeam: "134588",
            strAwayTeamBadge: null,
            intScore: null,
            intScoreVotes: null,
            strResult: null,
            idVenue: "16021",
            strVenue: "Estádio Do Dragão",
            strCountry: "Portugal",
            strCity: null,
            strPoster: "",
            strSquare: "",
            strFanart: null,
            strThumb:
                "https://www.thesportsdb.com/images/media/event/thumb/kfwoa51628862271.jpg",
            strBanner: "",
            strMap: null,
            strTweet1: null,
            strTweet2: null,
            strTweet3: null,
            strVideo: null,
            strStatus: "Match Finished",
            strPostponed: "no",
            strLocked: "unlocked",
        },
    ],
} as const;
